version = 1
SPDX-PackageName = "espeyu"
SPDX-PackageDownloadLocation = "https://github.com/abrahammenendez/espeyu"

[[annotations]]
path = [
    ".claude/**",
    ".commitlintrc.yml",
    ".github/**",
    ".gitignore",
    "LICENSE",
    "README.md",
    "app/src/test/screenshots/**",
    "docs/**",
    "fastlane/**",
    "gradle/*",
]
SPDX-FileCopyrightText = "2026 Abraham Menéndez"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = ["gradle/wrapper/**", "gradlew", "gradlew.bat"]
SPDX-FileCopyrightText = "Gradle Inc."
SPDX-License-Identifier = "Apache-2.0"
