name: Verify
on:
  workflow_call:
permissions:
  contents: read
jobs:
  verify:
    name: Lint, test, build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Android
        uses: ./.github/actions/set-up-android
      - name: Format
        run: ./gradlew spotlessCheck
      - name: Lint
        run: ./gradlew lint
      - name: Unit tests
        run: ./gradlew test
      - name: Build
        run: ./gradlew bundleRelease
      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: reports
          path: |
            app/build/reports/
            app/build/outputs/roborazzi/
            benchmark/build/reports/
          retention-days: 7
  licensing:
    name: REUSE compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Check licence headers
        uses: fsfe/reuse-action@v6
